---
#
# Installation ElasticSearch (pour les nuls)
#

# Installation ElasticSearch

- name: Installation Elasticsearch
  apt:
   name: elasticsearch
   update_cache: yes

# Activation ElasticSearch

- name: enable du service ElasticSearch
  systemd:
    name: elasticsearch
    enabled: yes

# Demarrage du service ElasticSearch

- name: Starting du service Elasticsearch
  service:
   name: elasticsearch
   state: started
...