---
#
# Installation Auditbeat
#

# Installation Auditbeat

- name: Install Auditbeat
  apt:
   name: auditbeat
   update_cache: yes

# Acces au setup de Kibana

- name: Configuration pour acces au setup de Kibana
  lineinfile:
   destfile: /etc/auditbeat/auditbeat.yml
   regexp: '$5601'
   line: '  hosts: 172.16.128.14:5601'


# Acces a ElasticSearch

- name: Configuration de l'acces a ElasticSearch
  lineinfile:
   destfile: /etc/auditbeat/auditbeat.yml
   regexp: '$9200'
   line: 'host: ["172.16.128.14:5044"]'

# Mise en place des dashboard

- name: Command run
  shell: "auditbeat setup"


# Activation auditbeat

- name: enable service auditbeat
  systemd:
    name: auditbeat
    enabled: yes

# Demarrage du service auditbeat

- name: Starting auditbeat
  service:
   name: auditbeat
   state: started
...